name: Deploy 100days to VPS
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production   # (facultatif) pour protéger la prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH agent with deploy key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Add VPS to known_hosts (strict)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SERVER_PORT || 22 }}" "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Install Ansible (runner)
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      # (Optionnel) pousser/MAJ tes playbooks sur le serveur
      - name: Rsync playbooks to server
        run: |
          rsync -az --delete ./ansible_hetzner/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/ansible_hetzner/

      # (Optionnel) déposer le mot de passe Vault côté serveur sans le logger
      - name: Write Ansible Vault password on server (optional)
        if: ${{ secrets.ANSIBLE_VAULT_PASS != '' }}
        run: |
          ssh -p "${{ secrets.SERVER_PORT || 22 }}" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "set -eu; cd ~/ansible_hetzner; umask 077; printf '%s' '${{ secrets.ANSIBLE_VAULT_PASS }}' > .vault_pass.txt"

      - name: Run deploy playbook remotely
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          ssh -p "${{ secrets.SERVER_PORT || 22 }}" ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
          set -eu
          cd ~/ansi
